baseURL = 'https://example.org/'
# baseURL = "http://localhost"

# Site language. Available translations in the theme's `/i18n` directory.
languageCode = 'en-us'
defaultContentLanguage = "en"
title = 'My New Hugo Site'
theme = 'ananke'

enableGitInfo = true
publishDir = 'public-hugo'
